GET http://localhost:5240/todos/api/v1
Authorization: Bearer <your_token>

### 
GET http://localhost:5240/todos/api/v1/2
Authorization: Bearer <your_token>

###
POST http://localhost:5240/todos/api/v1
Content-Type: application/json
Authorization: Bearer <your_token>

{
    "title": "Task-3 Update playlist",
    "text": "Gym playlist is a bit old, needs updating"
}

###
PUT http://localhost:5240/todos/api/v1/4
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "title": "Task 4 updated",
  "text": "Prepare for exam"
}

###
DELETE http://localhost:5240/todos/api/v1/5
Authorization: Bearer <your_token>






###
POST http://localhost:5240/users/login
Content-Type: application/json

{
  "Email": "will@outlook.com"
}







